name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
      - uses: browser-actions/setup-chrome@v1
        id: setup-chrome
      - run: echo "PUPPETEER_EXECUTABLE_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - run: npm test
      - run: npm run integrationTest
